### ISSUE TITLE
Issues spawning the controller

### ISSUE THREAD

**Issue by leocorp96** [Gauraviitkgp/Servo-Controller#1]
Hello, the controller manager seems unable to spawn the controllers defined in the servo.yaml file. Any suggestions on what maybe the cause??

Error message:
[WARN] [1553489794.674838, 28.573000]: Controller Spawner couldn't find the expected controller_manager ROS interface.

**Comment by Gauraviitkgp** [comment]
Hi @Leocorp ,
Thanks for reaching out. There seems to be an update for this repository since I created it a year back. Few Solutions which I suggest

1) Check the namespace of the ros-control gazebo plugin in the model.gazebo , i hope the namespace is kept same [https://answers.ros.org/question/198929/running-controller_manager-spawner-with-mybotrobot_description/](url)

2) There might be an update for the ros-control. You might want to run again
`sudo apt-get install ros-kinetic-ros-control ros-kinetic-ros-controllers`
`sudo apt-get install ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control`

Try these if things work then do tell me I'll include them in the README

**Comment by leocorp96** [comment]
Hello @Gauraviitkgp , 
1. So I checked the namespace and everything seemed ok.
2. Then I made the installs in the second step. Turns out I didn't have a few of the required packages installed.
3. And then I made a few modifications to the "servo.gazebo" file.

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/servo</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>false</legacyModeNS> 
    </plugin>
  </gazebo>

4. Everything works now and all topics are being published. I will be closing this issue now. Thanks.
